### ISSUE TITLE
Server web ui is not available often

### ISSUE THREAD

**Issue by vsapronov** [syncloud/server#5]
Sometimes web UI is just not responding. Even on internal ip-address.

**Comment by cyberb** [comment]
I think it takes really long time to initialize process per thread l, try
waiting and refreshing several times.

**Comment by vsapronov** [comment]
This I can't understand: What process per what thread? Why ownCloud is
showing it's UI always (and it's using the same apache). So far difference
is that server is on Python-Flask and ownCloud is on PHP...

**Comment by cyberb** [comment]
I am just observing, I am not saying it is correct. So if you see the
result after some time, then we are talking about the same issue.
Do you want to fix it?

**Comment by vsapronov** [comment]
No, I do not see result after some time. It was working good during some
time after activation, but after some time do not give responses. I need to
check logs probably.

I do not understand what process and threads you mean at all. You need to
explain to bring me to the same page...

**Comment by cyberb** [comment]
I do not understand it correctly as well, so disregard whatever I said. I
have seen huge delays after startup and thought it is related to
process/thread configuration
https://code.google.com/p/modwsgi/wiki/ProcessesAndThreading
No, I do not see result after some time. It was working good during some
time after activation, but after some time do not give responses. I need to
check logs probably.

I do not understand what process and threads you mean at all. You need to
explain to bring me to the same page...
On Mar 16, 2015 1:38 PM, "Boris Rybalkin" <notifications@github.com> wrote:

> I am just observing, I am not saying it is correct. So if you see the
> result after some time, then we are talking about the same issue.
> Do you want to fix it?
> On Mar 16, 2015 4:25 PM, "Vladimir Sapronov" <notifications@github.com>
> wrote:
>
> > This I can't understand: What process per what thread? Why ownCloud is
> > showing it's UI always (and it's using the same apache). So far
> difference
> > is that server is on Python-Flask and ownCloud is on PHP...
> > On Mar 16, 2015 12:22 PM, "Boris Rybalkin" <notifications@github.com>
> > wrote:
> >
> > > I think it takes really long time to initialize process per thread l,
> try
> > > waiting and refreshing several times.
> > > On Mar 16, 2015 3:24 PM, "Vladimir Sapronov" <notifications@github.com
> >
> > > wrote:
> > >
> > > > Sometimes web UI is just not responding. Even on internal
ip-address.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/syncloud/server/issues/5>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/syncloud/server/issues/5#issuecomment-81772987>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syncloud/server/issues/5#issuecomment-81775148>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/server/issues/5#issuecomment-81831605>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/syncloud/server/issues/5#issuecomment-81837724>.

**Comment by vsapronov** [comment]
OK, now I see what you meant. Yeah, this issue could be related to mod_wsgi
configuration.

**Comment by vsapronov** [comment]
One board was not working because was out of storage (resize failed) - not a problem of server.
On another board apache server just stopped, do not know why yet.

**Comment by vsapronov** [comment]
It was KILL_SERVICES=true doing that.
