### ISSUE TITLE
Support user_domain command

### ISSUE THREAD

**Issue by vsapronov** [syncloud/server#7]
This is the only command of insider used from android app. If there would be such a command in server then we could remove dependency. It seems to be very easy to implement with pass-through call from server to insider.

**Comment by vsapronov** [comment]
@cyberb If you don't have tasks this could be very useful and it's not hard to implement....

**Comment by cyberb** [comment]
Ideally this would be a secured rest call, but this is another story.

**Comment by vsapronov** [comment]
Yeah, we do ssh to server-cli anyway now. Think about iPhone in 0.9. Less
dependencies is always better there...
